export enum Estados {
    PAGO_PENDIENTE = 'PAGO_PENDIENTE',
    PAGO_RECHAZADO = 'PAGO_RECHAZADO',
    PENDIENTE = 'PENDIENTE',
    APROBADO = 'APROBADO',
    TERMINADO = 'TERMINADO',
    CANCELADO = 'CANCELADO',
    EN_DELIVERY = 'EN_DELIVERY',
    FACTURADO = 'FACTURADO'
}